### ISSUE TITLE
Customizable template?

### ISSUE THREAD

**Issue by halostatue** [simonecorsi/mawesome#14]
To be clear, I have absolutely no idea how this might be done, but I don’t necessarily want my list to be called my "awesome" list. Most of the stars that I make are sort of…bookmarks rather than anything curated.

Is there a way to customize the template?

**Comment by simonecorsi** [comment]
Hey, thanks for the feedback! 

> Is there a way to customize the template?

At the moment there isn't a way to provide a user-defined one, but the project uses an `ejs` [template](https://github.com/simonecorsi/mawesome/blob/main/src/template.ts) under the hood and it could be possible to change this to be the default while allowing users to input their own, both from a file in the repo or a string in workflow file, I'll give it a look but feel free to open a PR if you want!

**Comment by simonecorsi** [comment]
Hey @halostatue, sorry but the bot closed this too soon!

I've release v2 with custom template option, you can take a look on the README for usage!

**Comment by halostatue** [comment]
Thanks! I get the notice and will mark it unread so I can look at it later (I’m currently on vacation and not doing much on the computer).
