### ISSUE TITLE
about template

### ISSUE THREAD

**Issue by eryajf** [simonecorsi/mawesome#160]
I use this custom template: https://github.com/eryajf/awesome-stars-eryajf/blob/main/template/README.ejs

I got : https://github.com/eryajf/awesome-stars-eryajf

The results are not displayed according to the preset effect of the template.

**Comment by simonecorsi** [comment]
Hi @eryajf 👋 

Can you try changing your `template-path` with a relative path? 

https://github.com/eryajf/awesome-stars-eryajf/blob/main/.github/workflows/star-list.yml#L21
```diff
- template-path: "/template/README.ejs"
+ template-path: "template/README.ejs"
```

**Comment by eryajf** [comment]
thanks , it works.

**Comment by eryajf** [comment]
nice actions 👍

**Comment by eryajf** [comment]
Readme needs to be updated. I use the @latest version and cannot parse the template correctly.

change to  @v2  is ok

**Comment by simonecorsi** [comment]
Nice catch! 

I've updated `latest` to point to correct release
